### ISSUE TITLE
Ethernet is not working

### ISSUE THREAD

**Issue by tester89** [bluedrank/Z490i-Aorus-ultra-hackintosh#1]
I have same hardware as yours and used your EFI folder, but my ethernet is not working.

**Comment by bluedrank** [comment]
> I have same hardware as yours and used your EFI folder, but my ethernet is not working.

What version of macos are you using? I haven't tested all versions of MacOS but I found on MacOS 12 Ethernet doesn't work and I haven't fixed it yet. I have updated my EFI and found it working fine on MacOS 11(Bigsur) you can try it.

**Comment by tester89** [comment]
> 

Hi, thanks for the reply. I am using Monterey and it seems like ethernet doesn't work. So i bought USB to Ethernet cable and using it.
